apiVersion: v1
kind: Service
metadata:
  labels:
    app: sre-app-redis
  name: sre-app-redis-service
  namespace: sre-app-namespace
spec:
  type: ClusterIP
  ports:
    - name: redis-port
      port: 6379
      targetPort: 6379
  selector:
    app: sre-app-redis