apiVersion: apps/v1
kind: Deployment
metadata:
  name: sre-app-flask-deployment
  namespace: sre-app-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sre-app-flask
  template:
    metadata:
      labels:
        app: sre-app-flask
    spec:
      serviceAccountName: internal-app
      containers:
        - name: sre-app-flask-containers
          image: 422434854706.dkr.ecr.eu-west-1.amazonaws.com/bloomreach-simple-app:latest
          ports:
            - name: flask-app-port
              containerPort: 5000
          env:
            - name: REDIS_HOST
              value: "sre-app-redis-service"
            - name: REDIS_PORT
              value: "6379"
            - name: USERNAME
              value: "bob"
            - name: PASSWORD
              value: "thebuilder"
            - name: THEBIGSECRET
              value: "I love cookies."
      imagePullSecrets:
        - name: ecr-credentials