apiVersion: apps/v1
kind: Deployment
metadata:
  name: sre-app-flask-deployment
  namespace: sre-app-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sre-app-flask
  template:
    metadata:
      labels:
        app: sre-app-flask
    spec:
      containers:
        - name: sre-app-flask-containers
          image: 422434854706.dkr.ecr.eu-west-1.amazonaws.com/bloomreach-simple-app:latest
          ports:
            - name: flask-app-port
              containerPort: 5000
          env:
            - name: REDIS_HOST
              value: "sre-app-redis-service"
            - name: REDIS_PORT
              value: "6379"
            # TODO
            # Sensitive data hardcoding is temporary at this moment.
            # I am working on external vault integration with EKS cluster, but it's not working yet.
            # It should be ready on Monday interview.
            # The external vault:
            # https://www.jenkins-vault-bloomreach.com:8200/ui
            # I will use vault agent injector to achieve that.
            # https://learn.hashicorp.com/tutorials/vault/kubernetes-external-vault?in=vault/kubernetes
            - name: USERNAME
              value: "bob"
            - name: PASSWORD
              value: "thebuilder"
            - name: THEBIGSECRET
              value: "I love cookies."
      imagePullSecrets:
        - name: ecr-credentials
